###
POST http://localhost:8080/api/account/
Content-Type: application/json

{
  "fName": "emily",
  "lName": "milldrum",
  "email": "emily@test.com",
  "password": "test",
  "profilePic": "https://64.media.tumblr.com/4d1d96b07b7ffb8a974a52c31d84f337/9acaddb9bce6f4fd-7f/s540x810/7bfacef189d33bc2a7f1529b3fb5e664f30706f5.jpg",
  "posts": [{

  }],
  "comments": []
}

###
PUT http://localhost:8080/api/account/post
Content-Type: application/json

{
  "id": 1,
  "fName": "emily",
  "lName": "milldrum",
  "email": "emily@test.com",
  "password": "test",
  "profilePic": "https://64.media.tumblr.com/4d1d96b07b7ffb8a974a52c31d84f337/9acaddb9bce6f4fd-7f/s540x810/7bfacef189d33bc2a7f1529b3fb5e664f30706f5.jpg",
  "posts": [
    {
      "title": "my title",
      "createDate": "2012-04-23T18:25:43.511Z",
      "updateDate": "",
      "body": "this is the body",
      "comments": []
    }
  ],
  "comments": []
}


###
POST http://localhost:8080/api/post/
Content-Type: application/json

{
  "authorId": 1,
  "title": "my title 2",
  "createDate": "2022-04-23T18:25:43.511Z",
  "updateDate": "",
  "body": "this is the body again",
  "comments": []
}